### ISSUE TITLE
Upload latest to conan repository

### ISSUE THREAD

**Issue by Rwardc** [google/fruit#93]
Certain fixes, like those referenced by #89, have not yet been uploaded to JFrog.

**Comment by poletti-marco** [comment]
I know I need to do this (sorry) but I've been very busy and I currently don't have access to a Windows system to do this from.
I should get access again within ~2w.
Sorry for the inconvenience.

If you'd like to do this sooner and if there's some way for me to delegate access to you for this, I'd be happy to do so.

**Comment by Rwardc** [comment]
We've addressed the problem by checking out the source and doing a `conan create` locally on our build machine. If and when you update the JFrog repo, we'll switch back to grabbing it from there. 

Do you need the Windows system to run your regression tests?

**Comment by poletti-marco** [comment]
> Do you need the Windows system to run your regression tests?

Regression tests run on Appveyor and are still working.

I was planning to use that Windows system to create/upload the windows binaries.
But maybe you don't need that?

I now realized I could run "conan create" from my Linux system, so I've done that now if it helps.

**Comment by Rwardc** [comment]
Perfect. Yes, we just needed the updated `conanfile.py`. As long as that's up-to-date, then everything should be working fine on our end. I'll confirm that and get back to you.

**Comment by poletti-marco** [comment]
SG. Sorry, I'm totally not familiar with conan.
The Fruit conanfile was contributed by a user of Fruit, and I'm trying to maintain it as well as I can but I'm definitely not an expert.

If something is still missing please advise what to do and I can do it.
(e.g. maybe I should cut a new Fruit release before the "conan create"? Or is running that on the existing stable release, as I did now, enough?)

**Comment by tt4g** [comment]
@ph1ll  If the version of fruit being installed does not change, please do `conan upload`.

If the conan recipe provided by the conan community is also found to have build problems, it may do `conan upload` after correction.
This is because c++ is complex and it is difficult to provide a recipe that can be built successfully in all compiler.

The fix to make the build pass is always provided by the contributor, and as soon as it is fixed, it is upload to JFrog so that the conan consumer can use it.
